import type { HelpEntry, PageHelpContent } from "./types";

/** One source of truth for tooltips, expanded metric help, and page справка. */
export const HELP_METRICS: Record<string, HelpEntry> = {
  last_price: {
    id: "last_price",
    kind: "metric",
    title: "Последняя цена",
    summary: "Close последней доступной дневной RAW-свечи.",
    details:
      "Цена закрытия последнего торгового дня, который есть в market.candles. Это не adjusted и не total-return цена.",
    interpretation: "Сравнивайте с предыдущими close только в контексте RAW-истории.",
    limitations: ["Не учитывает дивиденды.", "Не пересчитывается после сплитов в этом UI."],
  },
  return_1d: {
    id: "return_1d",
    kind: "metric",
    title: "Доходность 1 день",
    summary: "Относительное изменение close за 1 торговый день.",
    details: "Базовый признак Analytics: (close_t − close_{t−1}) / close_{t−1} на точке as-of t.",
    interpretation: "Короткий шум; сам по себе не сигнал к сделке.",
    limitations: ["Нужна достаточная история.", "Считается по RAW close."],
    relatedIds: ["return_5d", "return_20d"],
  },
  return_5d: {
    id: "return_5d",
    kind: "metric",
    title: "Доходность 5 дней",
    summary: "Изменение close за 5 торговых дней.",
    details: "Окно ~одной торговой недели по дневным свечам.",
    interpretation: "Показывает краткосрочный импульс, не прогноз.",
    relatedIds: ["return_1d", "return_20d"],
  },
  return_20d: {
    id: "return_20d",
    kind: "metric",
    title: "Доходность 20 дней",
    summary: "Изменение close за ~20 торговых дней (~месяц).",
    details:
      "Используется в Analytics и как вход Technical. На экране инструмента показывается значение из активного feature set. Mechanical-adjusted V2 — отдельный расчётный контур, не замена RAW-графика котировок.",
    interpretation: "Среднесрочный импульс. Высокое значение ≠ рекомендация покупать.",
    limitations: [
      "Не вероятность прибыли.",
      "На инструментах с короткой историей может быть «Недостаточно истории».",
    ],
    relatedIds: ["return_5d", "rsi14", "confidence"],
  },
  volatility_5d: {
    id: "volatility_5d",
    kind: "metric",
    title: "Волатильность 5 дней",
    summary: "Краткосрочная вариативность доходностей.",
    details: "Оценка разброса дневных доходностей на окне 5 дней.",
    interpretation: "Высокая волатильность = шире разброс исходов, не направление.",
  },
  volatility_20d: {
    id: "volatility_20d",
    kind: "metric",
    title: "Волатильность 20 дней",
    summary: "Вариативность доходностей на ~месячном окне.",
    details: "Более устойчивая оценка шума, чем 5-дневная.",
    interpretation: "Сравнивайте внутри одного инструмента и режима рынка.",
  },
  drawdown_20d: {
    id: "drawdown_20d",
    kind: "metric",
    title: "Просадка 20 дней",
    summary: "Падение от локального максимума на окне 20 дней.",
    details: "Отрицательная величина: насколько close ниже недавнего пика.",
    interpretation: "Мера локального давления продаж, не «риск портфеля».",
  },
  volume_change_1d: {
    id: "volume_change_1d",
    kind: "metric",
    title: "Изменение объёма",
    summary: "Относительное изменение дневного объёма к предыдущему дню.",
    details: "Показывает всплеск или спад активности торгов.",
  },
  volume_zscore_20d: {
    id: "volume_zscore_20d",
    kind: "metric",
    title: "Z-score объёма 20д",
    summary: "Насколько текущий объём отклоняется от среднего за 20 дней.",
    details: "Z ≈ 0 — около нормы; |Z| > 2 — заметный выброс активности.",
    interpretation: "Подтверждение импульса, не самостоятельный сигнал.",
  },
  technical_score: {
    id: "technical_score",
    kind: "metric",
    title: "Score",
    summary: "Сводный балл rules_v1 по факторам тренда, моментума, RSI и объёма.",
    details:
      "Детерминированная rules-модель Technical Agent. Score — агрегат вкладов факторов, а не ожидаемая доходность.",
    interpretation: "Знак и величина отражают согласованность правил на as-of дате.",
    limitations: ["Не BUY/SELL.", "Не прогноз цены."],
    relatedIds: ["confidence", "rsi14"],
  },
  confidence: {
    id: "confidence",
    kind: "metric",
    title: "Confidence",
    summary: "Насколько согласован и полон сигнал (coverage × agreement × quality) — не вероятность прибыли.",
    details:
      "Считается как coverage × agreement × quality (0…1). Coverage — сколько факторов доступно; agreement — совпадают ли их знаки; quality — штраф за проблемы данных.",
    interpretation:
      "Высокий confidence значит «оценка собрана согласованно», а не «сделка с высокой вероятностью прибыли».",
    limitations: [
      "Это не вероятность прибыли и не калиброванная вероятность направления.",
      "При разрыве цены / невалидных данных сигнал обнуляется.",
    ],
    relatedIds: ["technical_score", "rsi14"],
  },
  rsi14: {
    id: "rsi14",
    kind: "metric",
    title: "RSI14",
    summary: "Индекс относительной силы за 14 торговых дней.",
    details:
      "Осциллятор моментума по дневным close. В rules_v1 — один из входов в score, а не самостоятельный торговый сигнал.",
    interpretation: "Зоны около 30/70 часто читают как перепроданность/перекупленность — в ProjectAI это вклад в оценку, не приказ.",
    limitations: ["На короткой истории может отсутствовать.", "Не использовать как единственное правило входа."],
    relatedIds: ["return_20d", "confidence"],
  },
  sma20_distance: {
    id: "sma20_distance",
    kind: "metric",
    title: "SMA20 dist",
    summary: "Относительное расстояние close к SMA(20).",
    details: "Положительное — цена выше средней; отрицательное — ниже.",
  },
  ema20_distance: {
    id: "ema20_distance",
    kind: "metric",
    title: "EMA20 dist",
    summary: "Относительное расстояние close к EMA(20).",
    details: "EMA быстрее реагирует на недавние close, чем SMA.",
  },
  atr14_pct: {
    id: "atr14_pct",
    kind: "metric",
    title: "ATR14%",
    summary: "Average True Range 14, нормированный к цене.",
    details: "Мера дневного «размаха» в процентах цены.",
    interpretation: "Выше ATR% — шире типичный дневной ход.",
  },
  pearson: {
    id: "pearson",
    kind: "metric",
    title: "Pearson",
    summary: "Линейная корреляция доходностей пары на окне.",
    details:
      "Relations Agent: статистическая связь двух inputs на выбранном окне наблюдений. Не причинность и не торговый сигнал.",
    interpretation: "Близко к ±1 — сильная линейная согласованность; около 0 — слабая.",
    limitations: ["Не означает lead-lag.", "Не рекомендация к парной торговле."],
    relatedIds: ["spearman", "best_lag", "relations_term"],
  },
  spearman: {
    id: "spearman",
    kind: "metric",
    title: "Spearman",
    summary: "Ранговая корреляция на том же окне.",
    details: "Устойчивее к выбросам, чем Pearson; всё ещё описательная статистика.",
    relatedIds: ["pearson"],
  },
  best_lag: {
    id: "best_lag",
    kind: "metric",
    title: "Best lag",
    summary: "Лучший лаг lead→follower по корреляции на профиле лагов.",
    details:
      "Эвристика синхронности/опережения на исторических доходностях. Не доказательство причинности и не гарантия будущего опережения.",
    limitations: ["Может меняться между as_of датами.", "Не торговый сигнал."],
    relatedIds: ["pearson", "relations_term"],
  },
  relations_term: {
    id: "relations_term",
    kind: "term",
    title: "Связи (Relations)",
    summary: "Статистическая структура рынка: корреляции и lead-lag, не BUY/SELL.",
    details:
      "Модуль Relations считает snapshots корреляций и лагов между inputs. Это слой описания структуры, а не исполнение сделок. Mechanical V2 adjustment — отдельный контур данных; UI показывает активный relation set.",
    interpretation: "Используйте для понимания «кто движется вместе», а не для автоматических ордеров.",
    limitations: [
      "Корреляция ≠ причинность.",
      "Окно и universe влияют на топ пар.",
      "Не активирует торговый контур.",
    ],
    relatedIds: ["pearson", "best_lag"],
  },
  raw_candles: {
    id: "raw_candles",
    kind: "term",
    title: "RAW свечи",
    summary: "Биржевые дневные OHLCV как пришли с биржи — без «сглаживания» сплитов.",
    details:
      "На графике котировок ProjectAI показывает RAW exchange candles (market.candles). Механические сплиты/деноминации не переписывают эти свечи: разрыв цены после сплита остаётся видимым. Отдельная analytical basis ProjectAI (mechanical-adjusted) используется в Analytics / Technical / Relations и не подменяет этот график.",
    limitations: [
      "Дивидендные гэпы тоже остаются как есть.",
      "Adjusted-график в этом UI не показывается — это сознательное разделение Prediction/Analytics vs сырых котировок.",
    ],
  },
  feature_coverage: {
    id: "feature_coverage",
    kind: "metric",
    title: "Покрытие инструментов",
    summary: "Сколько активных инструментов имеют рассчитанные признаки.",
    details: "Отношение instruments_with_features / instruments_active для активного feature set.",
  },
  data_quality: {
    id: "data_quality",
    kind: "metric",
    title: "Качество данных",
    summary: "Сводка DQ-замечаний по инструменту или рынку.",
    details: "Append-only журнал проблем качества: пропуски, скачки, пустые ответы источника и т.п.",
    interpretation: "«Без замечаний» не гарантирует идеальные данные навсегда — только отсутствие текущих записей DQ.",
  },
  sim_nav: {
    id: "sim_nav",
    kind: "metric",
    title: "NAV симуляции",
    summary: "Стоимость виртуального портфеля Historical Simulator V0 на дату.",
    details:
      "NAV = cash + сумма market value позиций по RAW close/open правилам исполнения. Это research ledger, не брокерский счёт.",
    interpretation: "Сравнивайте динамику NAV с нормализованным IMOEX на том же окне.",
    limitations: ["Не включает дивидендный cash в V0.", "Не реальное исполнение у брокера."],
    relatedIds: ["sim_cash", "sim_exposure"],
  },
  sim_cagr: {
    id: "sim_cagr",
    kind: "metric",
    title: "Доходность / CAGR",
    summary: "Price return портфеля (и CAGR при достаточной длине окна).",
    details:
      "total_price_return = final_nav / initial_nav − 1. CAGR считается только на достаточно длинных окнах. Тип возврата — price, не total return.",
    interpretation: "Отрицательная абсолютная доходность красится как убыток; это не то же самое, что относительный результат к IMOEX.",
    limitations: ["Без дивидендов.", "Не гарантия будущей прибыли."],
    relatedIds: ["sim_excess", "sim_max_drawdown"],
  },
  sim_volatility: {
    id: "sim_volatility",
    kind: "metric",
    title: "Волатильность портфеля",
    summary: "Годовая волатильность дневных доходностей NAV (research).",
    details: "Оценка разброса дневных return NAV, аннуализированная на 252 торговые дни.",
    interpretation: "Мера шума доходности, не направление.",
    relatedIds: ["sim_sharpe"],
  },
  sim_sharpe: {
    id: "sim_sharpe",
    kind: "metric",
    title: "Sharpe (rf=0)",
    summary: "Research Sharpe без безрисковой ставки — не брокерский реализм.",
    details: "Средняя дневная доходность / дневная σ, × √252, rf = 0. Нужна для сравнения режимов, не для отчётности инвестору.",
    limitations: ["rf=0.", "Чувствителен к окну и издержкам."],
    relatedIds: ["sim_volatility", "sim_cagr"],
  },
  sim_max_drawdown: {
    id: "sim_max_drawdown",
    kind: "metric",
    title: "Максимальная просадка",
    summary: "Худшее падение NAV от пика к дну на периоде симуляции.",
    details: "Считается по дневной серии NAV. UI показывает даты пика, дна и (если есть) восстановления.",
    interpretation: "Риск пути капитала, не «вероятность убытка».",
    relatedIds: ["sim_nav", "sim_cagr"],
  },
  sim_turnover: {
    id: "sim_turnover",
    kind: "metric",
    title: "Оборот",
    summary: "Отношение суммарного notional сделок к среднему NAV.",
    details: "Грубый proxy торговой активности. Высокий оборот усиливает влияние commission/slippage bps.",
    relatedIds: ["sim_commission", "sim_bps"],
  },
  sim_exposure: {
    id: "sim_exposure",
    kind: "metric",
    title: "Gross exposure",
    summary: "Суммарная рыночная стоимость длинных позиций.",
    details: "В long-only V0 совпадает с invested capital; cash хранится отдельно.",
    relatedIds: ["sim_cash", "sim_nav"],
  },
  sim_cash: {
    id: "sim_cash",
    kind: "metric",
    title: "Cash",
    summary: "Свободные денежные средства ledger на дату.",
    details: "Остаток после покупок/продаж и комиссий. Cash weight = cash / NAV.",
    relatedIds: ["sim_nav", "sim_exposure"],
  },
  sim_excess: {
    id: "sim_excess",
    kind: "metric",
    title: "Относительный результат (п.п.)",
    summary: "Разность price return портфеля и IMOEX в процентных пунктах.",
    details:
      "excess_vs_imoex = total_price_return_portfolio − total_price_return_IMOEX. Положительный excess при отрицательной абсолютной доходности означает «упали меньше индекса», а не «заработали».",
    interpretation: "Не путать с прибылью портфеля. В UI оформляется нейтрально, не как green profit.",
    limitations: ["IMOEX — price index.", "Не alpha в смысле CAPM."],
    relatedIds: ["sim_cagr"],
  },
  sim_bps: {
    id: "sim_bps",
    kind: "metric",
    title: "Издержки (bps)",
    summary: "Комиссия/проскальзывание в базисных пунктах на сделку.",
    details: "Упрощённая friction-модель V0. Cost-sensitivity сравнивает sibling-прогоны с разными bps.",
    relatedIds: ["sim_commission", "sim_slippage"],
  },
  sim_slippage: {
    id: "sim_slippage",
    kind: "metric",
    title: "Slippage (bps)",
    summary: "Модельное проскальзывание относительно raw open.",
    details: "Добавляется к цене исполнения в Historical Next Open adapter. Не рыночный impact-модель.",
    relatedIds: ["sim_bps", "sim_commission"],
  },
  sim_commission: {
    id: "sim_commission",
    kind: "metric",
    title: "Commission (bps)",
    summary: "Комиссия в bps от notional сделки.",
    details: "Списывается из cash при fill. Секция чувствительности показывает sibling SUCCESS runs.",
    relatedIds: ["sim_bps", "sim_turnover"],
  },
  sim_oos: {
    id: "sim_oos",
    kind: "term",
    title: "OOS / research-контекст",
    summary: "DEVELOPMENT_OOS и research-метка Candidate V0 (часто MIXED) — не gate прибыльности.",
    details:
      "Prediction ML Candidate V0 имеет research verdict MIXED. На дашборде симулятора это показывается как контекст исследования отдельно от engineering PASS. Нельзя читать MIXED как «модель прибыльна» или «готова к деньгам».",
    interpretation: "Сначала engineering status, затем research-контекст как осторожная пометка.",
    limitations: ["Не торговый сигнал.", "Не чемпион-статус."],
    relatedIds: ["sim_holdout"],
  },
  sim_holdout: {
    id: "sim_holdout",
    kind: "term",
    title: "FINAL_HOLDOUT",
    summary: "Финальный holdout-сегмент предсказаний — отдельный период от DEV OOS.",
    details:
      "Сравнение DEV vs HOLDOUT при 0 bps — образовательная таблица устойчивости на разных окнах, не proof of edge.",
    limitations: ["Один holdout не заменяет многократный walk-forward."],
    relatedIds: ["sim_oos"],
  },
  sim_rebalance: {
    id: "sim_rebalance",
    kind: "term",
    title: "Ребаланс",
    summary: "Weekly rebalance: целевые веса пересматриваются по политике на decision date.",
    details: "В V0 политика Rank Long-Only выбирает top quantile и задаёт target weights; ордера появляются в дни ребаланса.",
    relatedIds: ["sim_next_open"],
  },
  sim_next_open: {
    id: "sim_next_open",
    kind: "term",
    title: "Next open исполнение",
    summary: "Исполнение на следующем торговом open после decision date.",
    details: "HistoricalNextOpenAdapter: нет look-ahead на close дня решения. Fill price = raw open ± friction.",
    relatedIds: ["sim_rebalance", "sim_slippage", "decision_pending"],
  },
  decision_why: {
    id: "decision_why",
    kind: "term",
    title: "Почему была сделка?",
    summary:
      "Человекочитаемое объяснение из сохранённых фактов решения: прогноз, ранг, политика, риск, исполнение.",
    details:
      "Три уровня: краткое резюме, подробности правила политики, технические детали provenance. Текст строится детерминированно в UI из API-фактов. LLM не используется.",
    interpretation:
      "Модель даёт прогноз/ранг; политика задаёт целевую позицию; риск может ограничить экспозицию; исполнение — отдельный этап.",
    limitations: [
      "Не инвестиционная рекомендация.",
      "Не объясняет «почему цена потом выросла/упала».",
      "Неполная provenance → более короткое объяснение без выдуманных полей.",
    ],
    relatedIds: [
      "decision_pred_20d",
      "decision_rank",
      "decision_target_weight",
      "decision_policy",
      "decision_reason_code",
      "sim_next_open",
      "decision_pending",
      "decision_risk_guard",
      "decision_tech_provenance",
    ],
  },
  decision_pred_20d: {
    id: "decision_pred_20d",
    kind: "metric",
    title: "Predicted Return 20d",
    summary: "Прогноз модели механического изменения цены на 20 торговых дней (~месяц).",
    details:
      "Это forecast Candidate V0 по PIT-признакам, а не гарантированная доходность и не total return с дивидендами. Не рекомендация к покупке.",
    limitations: ["Не probability of profit.", "Не дивидендный total return."],
    relatedIds: ["decision_rank", "decision_why"],
  },
  decision_rank: {
    id: "decision_rank",
    kind: "metric",
    title: "Rank",
    summary: "Относительное место инструмента среди eligible прогнозов на дату.",
    details:
      "Rank 1 — наибольший predicted return 20d среди доступных на эту дату инструментов. Это не «лучшая компания».",
    relatedIds: ["decision_pred_20d", "decision_why"],
  },
  decision_target_weight: {
    id: "decision_target_weight",
    kind: "metric",
    title: "Target Weight",
    summary: "Целевая доля позиции, назначенная политикой на дату решения.",
    details:
      "Вес после policy (+ risk clamp, если применялся). Фактический fill может отличаться из‑за цен/кэша/округления.",
    relatedIds: ["decision_policy", "decision_why"],
  },
  decision_policy: {
    id: "decision_policy",
    kind: "term",
    title: "Policy",
    summary: "Правило, которое превращает прогнозы/ранги в целевые позиции.",
    details:
      "Например, рейтинговая стратегия с удержанием (Hysteresis V1): вход Top 20%, удержание до Top 35%, порог сделки 2 п.п. Модель сама не «покупает».",
    relatedIds: ["decision_reason_code", "decision_why"],
  },
  decision_reason_code: {
    id: "decision_reason_code",
    kind: "term",
    title: "Reason Code",
    summary: "Технический код причины ордера/решения (ENTER_TOP20, EXIT_BELOW_TOP35, …).",
    details:
      "В UI сначала показывается человеческое объяснение; код остаётся в технических деталях для аудита.",
    relatedIds: ["decision_why", "decision_tech_provenance"],
  },
  decision_pending: {
    id: "decision_pending",
    kind: "term",
    title: "Pending Order",
    summary: "Ордер создан, но ещё не исполнен — ждёт допустимое будущее открытие рынка.",
    details:
      "Для Shadow Portfolio fill запрещён на уже известных прошлых OPEN. Пока нет qualifying future open, корректный статус — PENDING.",
    relatedIds: ["sim_next_open", "decision_why"],
  },
  decision_risk_guard: {
    id: "decision_risk_guard",
    kind: "term",
    title: "Risk Guard",
    summary: "Ограничение экспозиции по собственной просадке портфеля (DRAWDOWN_GUARD_V1).",
    details:
      "При просадке ≤ −20% gross → 50%; при восстановлении ≥ −10% → 100%. Работает по Shadow/Simulator NAV этого портфеля, не по прогнозу модели.",
    relatedIds: ["decision_why", "sim_max_drawdown"],
  },
  decision_tech_provenance: {
    id: "decision_tech_provenance",
    kind: "term",
    title: "Technical provenance",
    summary: "Сырые поля решения/ордера/fill для аудита.",
    details:
      "Хеши, batch id, ranks, raw open, timestamps. Источник истины — persisted facts, не сгенерированный текст.",
    relatedIds: ["decision_why", "decision_reason_code"],
  },
  shadow_portfolio: {
    id: "shadow_portfolio",
    kind: "term",
    title: "Shadow Portfolio",
    summary: "Проспективный виртуальный портфель: решения и fills только после реальной активации.",
    details:
      "Не historical backtest и не Simulator replay. Использует immutable Forward Signal batches и ждёт будущие market opens.",
    relatedIds: ["forward_signal", "prospective_experiment", "pending_order"],
  },
  forward_signal: {
    id: "forward_signal",
    kind: "term",
    title: "Forward Signal",
    summary: "Иммутабельный live-прогноз Candidate V0 на последнюю завершённую рыночную дату.",
    details:
      "as_of — дата рыночных данных; generated_at — когда прогноз реально сформирован. Shadow может использовать batch только после generated_at.",
    relatedIds: ["signal_as_of", "signal_generated_at", "shadow_portfolio"],
  },
  prospective_experiment: {
    id: "prospective_experiment",
    kind: "term",
    title: "Проспективный эксперимент",
    summary: "Фиксация решений только после их фактического появления — без пересчёта прошлого.",
    details:
      "В отличие от Historical Simulator, Shadow не использует уже известные OPEN задним числом. Ноль fills в начале — корректный научный результат.",
    relatedIds: ["shadow_portfolio", "pending_order", "activation_date"],
  },
  activation_date: {
    id: "activation_date",
    kind: "term",
    title: "Дата запуска",
    summary: "Операционный timestamp активации Shadow-эксперимента.",
    details: "С этого момента начинается forward-наблюдение. История до activation не входит в Shadow NAV.",
    relatedIds: ["experiment_age", "prospective_experiment"],
  },
  pending_order: {
    id: "pending_order",
    kind: "term",
    title: "Ожидающий ордер",
    summary: "Ордер создан политикой, но ещё не исполнен на допустимом будущем OPEN.",
    details:
      "Нельзя называть такой ордер «купленным». Earliest execution date ограничивает backdating.",
    relatedIds: ["decision_pending", "market_watermark"],
  },
  market_watermark: {
    id: "market_watermark",
    kind: "term",
    title: "Market watermark",
    summary: "Последняя рыночная дата, уже обработанная Shadow advance.",
    details: "Предотвращает повторное исполнение. Пропуск до activation не создаёт фейковую NAV-историю.",
    relatedIds: ["shadow_portfolio", "pending_order"],
  },
  signal_as_of: {
    id: "signal_as_of",
    kind: "term",
    title: "Signal as_of",
    summary: "Рыночная дата, к которой относится PIT-прогноз.",
    details: "Это не момент доступности сигнала для Shadow. Доступность задаёт generated_at.",
    relatedIds: ["signal_generated_at", "forward_signal"],
  },
  signal_generated_at: {
    id: "signal_generated_at",
    kind: "term",
    title: "Signal generated_at",
    summary: "Когда Forward batch реально завершился и стал доступен.",
    details: "Исполнение Shadow возможно только на market date после календарной даты generated_at/decision.",
    relatedIds: ["signal_as_of", "prospective_experiment"],
  },
  risk_state: {
    id: "risk_state",
    kind: "term",
    title: "Risk state",
    summary: "Текущий режим риска портфеля (normal / risk_off).",
    details: "Для портфеля B Drawdown Guard меняет exposure cap по собственной NAV-истории.",
    relatedIds: ["decision_risk_guard", "shadow_portfolio"],
  },
  experiment_age: {
    id: "experiment_age",
    kind: "term",
    title: "Возраст эксперимента",
    summary: "Сколько дней прошло с activation.",
    details:
      "Несколько дней или недель forward-наблюдения недостаточны для оценки качества стратегии. CAGR/Sharpe рано не показываются.",
    relatedIds: ["activation_date", "forward_outcome_pending"],
  },
  forward_outcome_pending: {
    id: "forward_outcome_pending",
    kind: "term",
    title: "Ожидание 20d outcome",
    summary: "Реализованный 20-дневный исход модели ещё не наблюдается.",
    details: "Нужны будущие торговые наблюдения после as_of. Календарный countdown не используется.",
    relatedIds: ["decision_pred_20d", "experiment_age", "research_cycle"],
  },
  research_cycle: {
    id: "research_cycle",
    kind: "term",
    title: "Ежедневный исследовательский цикл",
    summary:
      "Оркестрация V0: рынок → Analytics/Technical/Relations V2 → Forward Signal → Shadow → outcome evaluation.",
    details:
      "Один прогон на актуальный watermark без historical backfill Forward. Статусы шагов вроде NO_CHANGES / SKIPPED_NOT_DUE — нормальные исходы, не ошибки.",
    relatedIds: ["daily_cycle_health", "forward_signal", "shadow_portfolio", "forward_outcome_pending"],
  },
  daily_cycle_health: {
    id: "daily_cycle_health",
    kind: "term",
    title: "Состояние контура",
    summary: "Сводка синхронизации рынка и downstream (Analytics / Technical / Forward / Shadow).",
    details:
      "IN_SYNC — контур догнал рынок; WAITING_FOR_MARKET — ждём новые данные; LAGGING — отставание; RUNNING — цикл идёт; BLOCKED — остановка.",
    relatedIds: ["research_cycle", "market_watermark", "forward_signal"],
  },
  research_lab: {
    id: "research_lab",
    kind: "term",
    title: "Лаборатория",
    summary:
      "Место, где на исторических данных проверяют гипотезы о стратегии — без реальных денег и без изменения живого эксперимента.",
    details:
      "Лаборатория запускает Historical Simulator V0 поверх уже зафиксированных прогнозов Prediction Candidate. Модель здесь не обучается и не переобучается: меняются только правила портфеля, риск-политика, издержки, период и стартовый капитал.",
    interpretation:
      "Хороший результат в Лаборатории — повод продолжить исследование, а не сигнал к сделке.",
    limitations: [
      "Это не брокерский P&L и не рекомендация.",
      "Живой эксперимент (Shadow) отсюда не изменяется.",
      "Повторный прогон на уже известном периоде не даёт нового рыночного опыта.",
    ],
    relatedIds: ["research_not_live", "development_oos", "observed_holdout", "sim_survivorship"],
  },
  research_not_live: {
    id: "research_not_live",
    kind: "term",
    title: "Исследование ≠ живая торговля",
    summary: "Результаты Лаборатории описывают прошлое; они не создают позиций и не управляют деньгами.",
    details:
      "Историческая симуляция показывает, как правило вело бы себя на уже известных данных. Это не проверка на будущем и не подтверждение прибыльности. Проспективная проверка идёт отдельно — в «Живом эксперименте».",
    interpretation: "Читайте цифры как описание сценария, а не как обещание доходности.",
    limitations: ["Нет исполнения у брокера.", "Нет дивидендов и total return.", "Universe с survivorship bias."],
    relatedIds: ["research_lab", "shadow_portfolio", "prospective_experiment"],
  },
  research_experiment: {
    id: "research_experiment",
    kind: "term",
    title: "Эксперимент",
    summary: "Один сохранённый прогон: модель + правило портфеля + риск + издержки + период + капитал.",
    details:
      "Эксперимент однозначно определяется своей конфигурацией. Название и заметка — только подпись для человека: они не входят в расчёт и не меняют config hash.",
    interpretation: "Сравнивать имеет смысл эксперименты, отличающиеся ровно одним условием.",
    relatedIds: ["config_hash", "experiment_reuse", "fair_comparison"],
  },
  development_oos: {
    id: "development_oos",
    kind: "term",
    title: "Development OOS",
    summary: "Исторические прогнозы вне обучающей выборки — рабочий полигон Лаборатории.",
    details:
      "Прогнозы на этом отрезке сделаны моделью на данных, которых не было в обучении. Это позволяет исследовать поведение правил портфеля, оставаясь внутри допустимого research-периода.",
    interpretation: "Подходит для сравнения стратегий между собой.",
    limitations: [
      "Отрезок один и тот же для всех запусков — это не многократный walk-forward.",
      "Многократные прогоны по одному периоду не добавляют независимого опыта.",
    ],
    relatedIds: ["observed_holdout", "research_period", "sim_oos"],
  },
  observed_holdout: {
    id: "observed_holdout",
    kind: "term",
    title: "Уже наблюдавшийся holdout",
    summary: "FINAL HOLDOUT уже использовался для оценки Candidate V0, поэтому он больше не независимый тест.",
    details:
      "Если настройку выбрали, посмотрев на holdout, то результат на нём перестаёт быть честной проверкой. Поэтому Лаборатория показывает такие прогоны только на чтение и запрещает запуск новых экспериментов на этом периоде.",
    interpretation: "Смотреть можно, использовать как доказательство выбора — нельзя.",
    limitations: ["Новые запуски на holdout заблокированы.", "Один holdout не заменяет walk-forward."],
    relatedIds: ["development_oos", "sim_holdout", "fair_comparison"],
  },
  candidate_model: {
    id: "candidate_model",
    kind: "term",
    title: "Модель-кандидат",
    summary:
      "Зафиксированная версия прогнозной модели; в Лаборатории она не обучается. V0 — прогноз изменения цены, V1 — рейтинговый балл.",
    details:
      "Candidate — это модель вместе с её конфигурацией и уже посчитанными прогнозами. Лаборатория берёт готовый артефакт прогнозов, поэтому результат воспроизводим. V0 (CatBoostRegressor) оценивает ожидаемое изменение цены за 20 торговых дней. V1 Ranker (CatBoostRanker) оценивает относительную привлекательность инструментов на дату — выход это рейтинговый балл для порядка, а не процент доходности. Список кандидатов приходит из API.",
    interpretation:
      "Research verdict (например MIXED) — контекст исследования, а не оценка прибыльности. Баллы разных моделей напрямую между собой не сравниваются.",
    limitations: [
      "Обучение и переобучение моделей из UI недоступно.",
      "V1 — только historical research; без Forward и без выбора по уже наблюдавшемуся 2026 HOLDOUT.",
    ],
    relatedIds: ["sim_oos", "config_hash", "ranking_model", "ranking_score"],
  },
  ranking_model: {
    id: "ranking_model",
    kind: "term",
    title: "Модель ранжирования",
    summary: "Модель, которая упорядочивает инструменты по относительной привлекательности на одну дату.",
    details:
      "В отличие от регрессии доходности, ranking-модель оптимизирует качество порядка внутри дня (cross-sectional). Candidate V1 Ranker обучается на YetiRank и выдаёт рейтинговый балл; портфельная политика использует этот порядок (Top 20% / Top 35%).",
    interpretation: "Выше балл → выше место в рейтинге на эту дату, не «выше % доходности».",
    limitations: [
      "Баллы разных моделей несопоставимы по величине.",
      "Не активируется в Forward/Shadow без отдельного решения.",
    ],
    relatedIds: ["ranking_score", "cross_sectional_rank", "rank_ic", "candidate_model"],
  },
  ranking_score: {
    id: "ranking_score",
    kind: "metric",
    title: "Рейтинговый балл",
    summary: "Выход модели ранжирования: число для упорядочивания инструментов, не процент доходности.",
    details:
      "Рейтинговый балл используется для порядка, а не как процент доходности. Шкала произвольна и зависит от конкретной версии модели; сравнивать абсолютные значения между V0 и V1 или разными прогонами нельзя.",
    interpretation: "Смотрите место в рейтинге и относительный порядок, а не «+1.37%».",
    limitations: ["Не калиброванный ожидаемый return.", "Не сравнивайте величину балла между моделями."],
    relatedIds: ["ranking_model", "cross_sectional_rank", "ranking_relevance"],
  },
  cross_sectional_rank: {
    id: "cross_sectional_rank",
    kind: "term",
    title: "Cross-sectional ранг",
    summary: "Место инструмента среди всех доступных на ту же дату по баллу модели.",
    details:
      "На каждую дату строится рейтинг по prediction score / ranking score. Политика берёт верхний квантиль этого рейтинга. Это относительное сравнение «кто привлекательнее сегодня», а не абсолютный прогноз цены.",
    interpretation: "Ранг 1 из 40 сильнее говорит о выборе, чем величина сырого балла.",
    relatedIds: ["ranking_score", "rank_ic", "portfolio_policy"],
  },
  rank_ic: {
    id: "rank_ic",
    kind: "metric",
    title: "Rank IC",
    summary:
      "Насколько порядок инструментов от модели совпал с фактическим порядком доходностей через 20 торговых дней.",
    details:
      "Обычно Spearman-корреляция рангов прогноза и realized return внутри даты, усреднённая по дням. Положительный Rank IC: выше в рейтинге модели чаще оказывались инструменты с лучшей фактической доходностью. Около нуля — слабая связь. Отрицательный — порядок чаще был обратным.",
    interpretation: "Это качество ранжирования, не доказательство прибыльности портфеля и не статистическая значимость «из коробки».",
    limitations: ["Не portfolio Sharpe.", "Не гарантия edge на будущем периоде."],
    relatedIds: ["icir", "top_bottom_spread", "ranking_model"],
  },
  icir: {
    id: "icir",
    kind: "metric",
    title: "ICIR",
    summary: "Отношение среднего Rank IC к изменчивости Rank IC во времени.",
    details:
      "IC Information Ratio ≈ mean(Rank IC) / std(Rank IC) по датам. Показывает, насколько стабилен сигнал ранжирования день ото дня.",
    interpretation: "Это не Sharpe портфеля и не метрика доходности стратегии.",
    limitations: ["Не portfolio Sharpe.", "Чувствителен к числу дат и выбросам IC."],
    relatedIds: ["rank_ic", "sim_sharpe"],
  },
  top_bottom_spread: {
    id: "top_bottom_spread",
    kind: "metric",
    title: "Top−Bottom spread",
    summary: "Разница средней фактической доходности верхнего и нижнего квантиля рейтинга модели.",
    details:
      "Диагностика: если модель хорошо ранжирует, верхняя корзина (например Top 20%) в среднем опережает нижнюю на горизонте 20 торговых дней. Считается по realized returns, не по баллу модели.",
    interpretation: "Положительный spread поддерживает ranking-качество; отрицательный — сигнал слабый или обратный.",
    limitations: ["Не учитывает издержки и оборот портфеля.", "Зависит от выбранного квантиля."],
    relatedIds: ["rank_ic", "ranking_score", "sim_turnover"],
  },
  ranking_relevance: {
    id: "ranking_relevance",
    kind: "term",
    title: "Ranking relevance",
    summary: "Целевая метка для обучения ranker: относительная привлекательность внутри даты, не сырой % return.",
    details:
      "Для Candidate V1 forward return преобразуется в cross-sectional percentile relevance на дату (лучший день получает 1, худший — 0). Модель учится воспроизводить этот порядок; выход — рейтинговый балл, а не калиброванный процент.",
    interpretation: "Relevance — учебная цель; в UI симуляции показывается ranking score / ранг.",
    limitations: ["Использует будущую доходность только как Y для обучения/оценки, не как feature X(t)."],
    relatedIds: ["ranking_score", "ranking_model", "cross_sectional_rank"],
  },
  portfolio_policy: {
    id: "portfolio_policy",
    kind: "term",
    title: "Правило портфеля",
    summary: "Как прогнозы модели превращаются в позиции: что покупать, сколько держать, когда менять.",
    details:
      "Правила зафиксированы версиями. «Базовая рейтинговая» каждую неделю берёт верхние 20 % рейтинга равными долями. «Рейтинговая с удержанием» входит из Top 20 %, но держит позицию до выхода за Top 35 %, что снижает лишнюю ротацию.",
    interpretation: "Меньше ротации — меньше издержек, но медленнее реакция на изменение рейтинга.",
    limitations: ["Параметры правил не редактируются в UI: это версионируемые контракты, а не ползунки."],
    relatedIds: ["risk_policy", "decision_policy", "sim_turnover"],
  },
  risk_policy: {
    id: "risk_policy",
    kind: "term",
    title: "Риск-политика",
    summary: "Ограничения, которые могут уменьшить или заблокировать позицию, предложенную правилом портфеля.",
    details:
      "«Базовые ограничения» — только длинные позиции, без плеча, не более 20 % на инструмент. «Защита от глубокой просадки» дополнительно снижает экспозицию до 50 % при просадке ниже −20 % и возвращает 100 % после восстановления выше −10 %.",
    interpretation: "Риск-политика не улучшает прогноз — она ограничивает размер ставки.",
    relatedIds: ["portfolio_policy", "decision_risk_guard", "sim_max_drawdown"],
  },
  simulation_cost: {
    id: "simulation_cost",
    kind: "term",
    title: "Издержки сделки (bps)",
    summary: "1 bps = 0,01 процентного пункта; 10 bps = 0,1 % от суммы сделки.",
    details:
      "Пресеты Лаборатории задают commission_bps и оставляют slippage равным нулю. Комиссия списывается от abs(notional) каждой сделки, поэтому влияние издержек тем больше, чем выше оборот портфеля.",
    interpretation:
      "Сценарий 0 bps показывает «чистое» поведение правила; 20 bps — насколько результат держится при дорогом исполнении.",
    limitations: ["Это условная модель трения, а не реальные тарифы брокера.", "Нет модели рыночного воздействия."],
    relatedIds: ["sim_commission", "sim_turnover", "comparison_family"],
  },
  research_period: {
    id: "research_period",
    kind: "term",
    title: "Период исследования",
    summary: "Окно дат внутри доступного Development OOS покрытия.",
    details:
      "Период можно сузить, но не выйти за границы имеющихся прогнозов. Короткое окно (меньше ~180 календарных дней) даёт нестабильные выводы: одна-две сделки могут определить весь результат.",
    interpretation: "Сравнивайте стратегии на одинаковом периоде — иначе сравнение нечестное.",
    limitations: ["Разные периоды делают метрики несопоставимыми."],
    relatedIds: ["development_oos", "fair_comparison"],
  },
  fair_comparison: {
    id: "fair_comparison",
    kind: "term",
    title: "Сопоставимые условия",
    summary:
      "Эксперименты сравнимы, если совпадают период, политика, риск, издержки, капитал и исполнение; модель может отличаться (A/B моделей).",
    details:
      "Fair badge «Сопоставимые условия» ставится, когда совпадают сегмент, даты, policy, risk, commission, капитал и правила исполнения. Различие candidate_config_hash / модели допускается — это как раз честное сравнение V0 vs V1. Если различаются политика, риск, период или издержки, UI показывает «Условия различаются» и перечисляет отличия.",
    interpretation:
      "Самое полезное сравнение моделей — когда отличается только Candidate при фиксированной политике и риске.",
    limitations: ["Совпадение условий не делает результат статистически значимым."],
    relatedIds: ["research_period", "comparison_family", "config_hash", "candidate_model"],
  },
  config_hash: {
    id: "config_hash",
    kind: "term",
    title: "Config hash",
    summary: "Отпечаток конфигурации эксперимента: одинаковый hash — одинаковая математика.",
    details:
      "Hash считается по спецификации симуляции (модель, правило, риск, издержки, капитал, исполнение). Человеческое название и заметка в него не входят, поэтому переименование не создаёт новый эксперимент.",
    interpretation: "Совпадение hash — причина, по которой Лаборатория переиспользует готовый результат.",
    relatedIds: ["experiment_reuse", "research_experiment"],
  },
  experiment_reuse: {
    id: "experiment_reuse",
    kind: "term",
    title: "Переиспользование результата",
    summary: "Идентичная конфигурация не пересчитывается — открывается уже сохранённый прогон.",
    details:
      "Повторный запуск того же config hash на том же периоде и капитале не добавляет знания, только время. Лаборатория возвращает существующий эксперимент и явно сообщает об этом.",
    interpretation: "Чтобы получить новый результат, измените условие, а не нажимайте «Запустить» повторно.",
    relatedIds: ["config_hash", "research_experiment"],
  },
  comparison_family: {
    id: "comparison_family",
    kind: "term",
    title: "Семейство издержек",
    summary: "Набор одинаковых экспериментов, отличающихся только комиссией (0 / 5 / 10 / 20 bps).",
    details:
      "Полное семейство позволяет увидеть чувствительность стратегии к трению: насколько результат съедается издержками при том же обороте.",
    interpretation: "Стратегия, которая выживает только при 0 bps, практически неинтересна.",
    limitations: ["Семейство собирается только из уже сохранённых прогонов."],
    relatedIds: ["simulation_cost", "sim_turnover", "fair_comparison"],
  },
  quick_comparison: {
    id: "quick_comparison",
    kind: "term",
    title: "Пакет сравнения",
    summary: "Фиксированный набор конфигураций, запускаемый одной кнопкой — это не оптимизация.",
    details:
      "Пакет прогоняет заранее заданную матрицу «правило × риск × издержки». Он не ищет лучшие параметры и не подбирает их под период: набор задан заранее и не зависит от результатов.",
    interpretation: "Цель — обзор поведения, а не выбор победителя.",
    limitations: ["Уже существующие конфигурации переиспользуются, а не пересчитываются."],
    relatedIds: ["comparison_family", "fair_comparison", "experiment_reuse"],
  },
  model_quality: {
    id: "model_quality",
    kind: "term",
    title: "Качество модели",
    summary:
      "Насколько модель упорядочивает будущие относительные доходности инструментов на одну дату.",
    details:
      "Отвечает на вопрос «умеет ли модель ранжировать?». Основные индикаторы: Rank IC, качество верхней части списка, стабильность порядка. Это ещё не доказательство прибыльного портфеля.",
    interpretation: "Сильное ранжирование ≠ автоматически сильная стратегия.",
    relatedIds: ["rank_ic", "top_tail_quality", "portfolio_translation"],
  },
  portfolio_translation: {
    id: "portfolio_translation",
    kind: "term",
    title: "Перевод в портфель",
    summary:
      "Превращается ли качество рейтинга в полезный портфель при выбранной стратегии, риске и издержках.",
    details:
      "Стратегия покупает верхнюю часть рейтинга, поэтому хороший общий Rank IC не гарантирует хороший портфель. Смотрите Top-tail, оборот, просадку и результат при одинаковой политике.",
    interpretation: "Разрыв между Rank IC и портфелем — нормальный исследовательский сигнал.",
    relatedIds: ["top_tail_quality", "model_quality", "portfolio_policy"],
  },
  economic_viability: {
    id: "economic_viability",
    kind: "term",
    title: "Экономический смысл",
    summary:
      "Оправдывал ли исторический результат стратегии принятый рыночный риск относительно денежной альтернативы.",
    details:
      "Сравнение с фиксированной годовой ставкой (cash hurdle) и просадкой. Это исследовательский post-processing, не торговый сигнал и не рекомендация.",
    interpretation: "Выше денежной альтернативы — интереснее для дальнейшего исследования; ниже — слабый экономический смысл на этом окне.",
    limitations: ["Не обещание будущей доходности.", "Не тариф депозита конкретного банка."],
    relatedIds: ["cash_hurdle", "excess_vs_cash", "break_even_cost"],
  },
  cash_hurdle: {
    id: "cash_hurdle",
    kind: "term",
    title: "Денежная альтернатива",
    summary:
      "Условная денежная альтернатива. Она нужна, чтобы понять, оправдывал ли исторический результат стратегии принятый рыночный риск. 10% здесь — исследовательский benchmark, а не обещанная ставка конкретного банка.",
    details:
      "Фиксированная годовая ставка компаундируется по календарным дням периода: (1+r)^(days/365.25)−1. Сравнение выполняется после симуляции и никогда не записывается в кэш/NAV портфеля. Выбор ставки в UI не меняет config hash.",
    interpretation: "Меняйте ставку, чтобы проверить чувствительность вывода — симуляция при этом не пересчитывается.",
    limitations: ["Не банковский депозит.", "Не часть Execution Adapter."],
    relatedIds: ["excess_vs_cash", "rate_based_cash_proxy", "economic_viability"],
  },
  rate_based_cash_proxy: {
    id: "rate_based_cash_proxy",
    kind: "term",
    title: "Ставочный денежный ориентир",
    summary: "Эквивалент капитала, оставленного под фиксированную годовую ставку на тот же календарный период.",
    details:
      "Считается только из дат и выбранной ставки. Не использует рыночные котировки облигаций и не моделирует налоги/реинвестирование купонов.",
    relatedIds: ["cash_hurdle", "excess_vs_cash"],
  },
  excess_vs_cash: {
    id: "excess_vs_cash",
    kind: "metric",
    title: "Разница vs денежная альтернатива",
    summary: "Доходность стратегии минус доходность выбранной денежной альтернативы за тот же период.",
    details:
      "Положительное значение — стратегия обогнала выбранный cash hurdle на этом окне; отрицательное — отстала. Это процентные пункты разницы, не «гарантированный edge».",
    interpretation: "Читайте вместе с просадкой и оборотом.",
    relatedIds: ["cash_hurdle", "economic_viability", "sim_excess"],
  },
  top_tail_quality: {
    id: "top_tail_quality",
    kind: "metric",
    title: "Качество верхней части рейтинга",
    summary:
      "Стратегия покупает не весь рейтинг, а только верхнюю его часть. Поэтому модель может иметь приемлемый общий Rank IC, но плохо выбирать именно те бумаги, которые попадают в портфель.",
    details:
      "Смотрите фактическую доходность Top 5/10/20/30%, hit-rate и долю «мусорных» бумаг в топе (loser contamination). Это объясняет разрыв между общим Rank IC и портфелем.",
    relatedIds: ["top_k_precision", "top_k_recall", "loser_contamination", "portfolio_translation"],
  },
  top_k_precision: {
    id: "top_k_precision",
    kind: "metric",
    title: "Точность Top-K",
    summary: "Доля бумаг из верхней части рейтинга модели, которые действительно оказались сильными по факту.",
    details: "Диагностика hit-rate / precision@K на горизонте 20 торговых дней.",
    relatedIds: ["top_tail_quality", "top_k_recall"],
  },
  top_k_recall: {
    id: "top_k_recall",
    kind: "metric",
    title: "Полнота Top-K",
    summary: "Насколько верх рейтинга модели покрывает фактически лучшие инструменты даты.",
    details: "Recall@K: доля истинных лидеров, попавших в предсказанный топ.",
    relatedIds: ["top_tail_quality", "top_k_precision"],
  },
  loser_contamination: {
    id: "loser_contamination",
    kind: "metric",
    title: "Загрязнение топа слабыми бумагами",
    summary: "Как часто в верхнюю часть рейтинга попадают инструменты с слабым фактическим исходом.",
    details:
      "Высокая loser contamination при хорошем общем Rank IC — типичная причина слабого портфеля: стратегия покупает «грязный» топ.",
    relatedIds: ["top_tail_quality", "portfolio_translation"],
  },
  rank_stability: {
    id: "rank_stability",
    kind: "metric",
    title: "Стабильность рейтинга",
    summary:
      "Показывает, насколько сильно меняется порядок инструментов от одной даты к другой. Очень нестабильный рейтинг может увеличивать количество перестановок и издержки.",
    details:
      "Смотрите корреляцию рангов неделя к неделе, среднее смещение ранга, persistence Top20/Top35 и churn входов/выходов. Стабильность ≠ качество прогноза.",
    interpretation: "Стабильный рейтинг может уменьшать лишние сделки, но сам по себе не означает edge.",
    relatedIds: ["rank_churn", "rank_persistence", "sim_turnover"],
  },
  rank_churn: {
    id: "rank_churn",
    kind: "metric",
    title: "Смена состава рейтинга",
    summary: "Сколько инструментов входит и выходит из верхней зоны между датами перебалансировки.",
    details: "Высокий churn при ненулевых издержках съедает результат даже при среднем Rank IC.",
    relatedIds: ["rank_stability", "sim_turnover"],
  },
  rank_persistence: {
    id: "rank_persistence",
    kind: "metric",
    title: "Удержание места в топе",
    summary: "Доля инструментов, которые остаются в Top 20 / Top 35 от одной даты к следующей.",
    details: "Полезно для hysteresis-политик: выше persistence — меньше вынужденных ротаций.",
    relatedIds: ["rank_stability", "portfolio_policy"],
  },
  model_disagreement: {
    id: "model_disagreement",
    kind: "term",
    title: "Расхождение моделей",
    summary: "Где V0 и V1 по-разному ранжируют и отбирают инструменты на одну и ту же дату.",
    details:
      "Side-by-side: ранги, факт попадания в портфель и realized 20d. Фильтр «Только расхождения» помогает искать решения, которые реально меняют портфель.",
    relatedIds: ["decision_attribution", "rank_correlation"],
  },
  decision_attribution: {
    id: "decision_attribution",
    kind: "term",
    title: "Атрибуция решения",
    summary: "Связь конкретного выбора модели (включить / не включить) с последующим фактическим исходом.",
    details:
      "Исторический факт: «V0 купила X, V1 нет; через 20 торговых наблюдений X показал …». Не рекомендация и не доказательство причинности beyond the sample.",
    relatedIds: ["model_disagreement", "portfolio_translation"],
  },
  regime_analysis: {
    id: "regime_analysis",
    kind: "term",
    title: "Анализ режимов",
    summary: "Как качество модели и портфеля выглядит в разных годах / рыночных режимах.",
    details:
      "Разбивка по году, тренду, волатильности или ставкам. Малое число наблюдений в ячейке — предварительный сигнал, не вердикт.",
    relatedIds: ["model_quality", "sample_maturity"],
  },
  paired_prospective_model: {
    id: "paired_prospective_model",
    kind: "term",
    title: "Парное проспективное сравнение",
    summary: "Две модели получают один срез признаков; отличается только модель; исполнение только вперёд.",
    details:
      "PROSPECTIVE_MODEL_AB_V0: без исторического paired backfill. Пустой старт после активации — нормально: ждём новый рыночный день.",
    limitations: ["Не объявлять победителя при малой зрелости выборки."],
    relatedIds: ["sample_maturity", "prospective_experiment", "rank_correlation"],
  },
  sample_maturity: {
    id: "sample_maturity",
    kind: "term",
    title: "Зрелость выборки",
    summary: "Сколько зрелых дат уже накопилось для честной оценки проспективного эксперимента.",
    details:
      "0 — слишком рано; 1–4 — очень мало; 5–19 — предварительные данные; 20–49 — история начинает накапливаться; 50+ — более содержательная выборка, но всё ещё не «доказательство навсегда».",
    relatedIds: ["paired_prospective_model", "forward_outcome_pending"],
  },
  rank_correlation: {
    id: "rank_correlation",
    kind: "metric",
    title: "Корреляция рангов моделей",
    summary: "Насколько порядок инструментов у V0 и V1 совпадает на одну дату.",
    details:
      "Высокая корреляция значит модели «думают похоже», но не говорит, какая права. Смотрите вместе с Top20 overlap.",
    relatedIds: ["top20_overlap", "model_disagreement"],
  },
  top20_overlap: {
    id: "top20_overlap",
    kind: "metric",
    title: "Пересечение Top 20",
    summary: "Доля общего состава верхней пятой части рейтинга между двумя моделями.",
    details: "Низкое пересечение — модели выбирают разные портфели при той же политике входа.",
    relatedIds: ["rank_correlation", "model_disagreement"],
  },
  break_even_cost: {
    id: "break_even_cost",
    kind: "metric",
    title: "Порог безубыточных издержек",
    summary: "При каких условных издержках исторический результат стратегии перестаёт быть интересным.",
    details:
      "Диагностика чувствительности к трению по семейству 0/5/10/20 bps. Не тариф брокера.",
    relatedIds: ["simulation_cost", "economic_viability", "comparison_family"],
  },
  sim_survivorship: {
    id: "sim_survivorship",
    kind: "term",
    title: "Survivorship и прочие лимиты",
    summary: "Текущая активная когорта инструментов может смещать историю «в пользу выживших».",
    details:
      "Universe current_active_instruments — fixed/current cohort. Плюс: нет дивидендного cash, IMOEX price-only, упрощённые bps, research ≠ trading.",
    limitations: [
      "Survivorship bias.",
      "Price return без дивидендов.",
      "Не брокерский P&L.",
    ],
    relatedIds: ["sim_oos", "sim_excess", "survivorship_bias", "historical_universe"],
  },
  external_history: {
    id: "external_history",
    kind: "term",
    title: "Внешний исторический архив",
    summary: "Неканонический CSV с длинной дневной историей для исследования.",
    details:
      "Источник EXTERNAL_30Y_CSV_V0 хранится в staging-таблицах market.external_*. Он не заменяет официальные MOEX RAW-свечи в рабочем контуре.",
    interpretation: "Смотрите семантику цен и сверку с MOEX до любых исследовательских выводов.",
    limitations: ["Не загружается из браузера.", "Не пишет в market.candles."],
    relatedIds: ["canonical_market_data", "source_precedence", "raw_price"],
  },
  raw_price: {
    id: "raw_price",
    kind: "term",
    title: "RAW-цена",
    summary: "Биржевая цена как наблюдение, без back-adjustment по сплитам/дивидендам.",
    details:
      "Canonical market.candles хранит RAW OHLCV. Скорректированные ряды выглядят «глаже», но меняют смысл скачков вокруг корпоративных действий.",
    relatedIds: ["adjusted_price", "canonical_market_data"],
  },
  adjusted_price: {
    id: "adjusted_price",
    kind: "term",
    title: "Скорректированная цена",
    summary: "Ряд, пересчитанный после сплитов/обратных сплитов (иногда и дивидендов).",
    details:
      "Если исторические цены делятся/умножаются на фактор корпоративного действия, а после события совпадают с MOEX, ряд скорее adjusted. Такие цены нельзя молча писать в RAW candles.",
    relatedIds: ["raw_price", "source_reconciliation"],
  },
  historical_universe: {
    id: "historical_universe",
    kind: "term",
    title: "Исторический universe",
    summary: "Набор инструментов, реально доступных на дату t, а не только сегодняшняя когорта.",
    details:
      "Текущий operational universe (~43) — отдельный контур. Архив расширяет исследовательский список, но не меняет Forward/Shadow автоматически.",
    relatedIds: ["survivorship_bias", "research_eligible"],
  },
  survivorship_bias: {
    id: "survivorship_bias",
    kind: "term",
    title: "Смещение выживаемости",
    summary: "Обучение только на компаниях, доживших до сегодня, завышает прошлое.",
    details:
      "Если обучать модель только на компаниях, которые дожили до сегодняшнего дня, в прошлом искусственно отсутствуют компании, которые были исключены, обанкротились или перестали торговаться. Это может сделать исторический результат слишком хорошим.",
    interpretation: "Архив снижает когортный bias ProjectAI, но не доказывает полное устранение delisting bias.",
    relatedIds: ["historical_universe", "sim_survivorship"],
  },
  source_reconciliation: {
    id: "source_reconciliation",
    kind: "term",
    title: "Сверка источника",
    summary: "Сравнение внешнего CSV с canonical MOEX на пересекающихся датах.",
    details:
      "Считаются exact OHLC, относительные расхождения close/volume и probes вокруг известных сплитов.",
    relatedIds: ["source_precedence", "adjusted_price"],
  },
  source_precedence: {
    id: "source_precedence",
    kind: "term",
    title: "Приоритет источников",
    summary: "На пересечении дат MOEX важнее внешнего архива.",
    details: "External CSV может дополнять только аудированные периоды вне MOEX coverage и никогда не перезаписывает market.candles.",
    relatedIds: ["canonical_market_data", "external_history"],
  },
  ticker_identity: {
    id: "ticker_identity",
    kind: "term",
    title: "Идентичность тикера",
    summary: "Равенство тикера ≠ автоматически тот же эмитент; неравенство ≠ другой эмитент.",
    details:
      "Переходы вроде YNDX→YDEX или TCSG→T не угадываются. Источнику оставляем его символ, пока нет доказанной идентичности.",
    relatedIds: ["historical_universe", "external_history"],
  },
  coverage: {
    id: "coverage",
    kind: "term",
    title: "Покрытие истории",
    summary: "Сколько инструментов и строк доступно по годам.",
    details: "Ранние годы архива часто разрежены; плотность растёт к 2010–2024.",
    relatedIds: ["historical_universe", "research_eligible"],
  },
  research_eligible: {
    id: "research_eligible",
    kind: "term",
    title: "Research eligible",
    summary: "Строка/тикер допущены к исследовательскому слою после качества и семантики.",
    details:
      "Eligible ≠ operational universe. Dataset V2 на 90 признаках может быть недоступен даже при eligible price history.",
    relatedIds: ["external_history", "raw_price"],
  },
  price_jump: {
    id: "price_jump",
    kind: "term",
    title: "Ценовой скачок",
    summary: "Крупное close-to-close изменение — диагностика, не авто-ошибка.",
    details:
      "Причины: сплиты, неликвидность, reuse тикера, плохие данные, деноминация. Автоматически не чиним и не помечаем как invalid.",
    relatedIds: ["adjusted_price", "raw_price"],
  },
  canonical_market_data: {
    id: "canonical_market_data",
    kind: "term",
    title: "Канонические рыночные данные",
    summary: "market.candles — официальный RAW-контур ProjectAI (MOEX).",
    details: "Внешний архив живёт отдельно. Любое обогащение канона требует RAW-совместимости и явного precedence.",
    relatedIds: ["raw_price", "source_precedence"],
  },
  fundamental_data: {
    id: "fundamental_data",
    kind: "term",
    title: "Фундаментальные данные",
    summary: "Финансовая отчётность, факты и события эмитента с учётом даты, когда они стали известны.",
    details:
      "Это не RSS-новости и не инвестиционные рекомендации. Контур хранит отчёты, дивиденды и корпоративные события для PIT-исследований и будущих признаков Dataset V3.",
    interpretation: "Пустые значения при отложенных провайдерах — честное состояние, не «нулевой сигнал».",
    limitations: [
      "Не торговый совет.",
      "Нельзя подставлять scraped disclosure без known_at.",
      "Не обучает модель из UI.",
    ],
    relatedIds: ["financial_report", "known_at", "point_in_time", "corporate_event"],
  },
  financial_report: {
    id: "financial_report",
    kind: "term",
    title: "Финансовый отчёт",
    summary: "Периодическая отчётность эмитента (IFRS/RAS) с датой публикации и known_at.",
    details:
      "Отчёт относится к отчётному периоду, но модель может использовать его только после даты, когда информация могла стать известна рынку.",
    relatedIds: ["reporting_period", "publication_date", "known_at", "IFRS", "RAS"],
  },
  reporting_period: {
    id: "reporting_period",
    kind: "term",
    title: "Отчётный период",
    summary: "Экономический интервал отчёта (квартал, полугодие, год) — не дата публикации.",
    details:
      "Период описывает, о каком времени говорится в цифрах. Дата публикации и known_at отвечают на вопрос «когда это стало известно».",
    relatedIds: ["financial_report", "publication_date"],
  },
  publication_date: {
    id: "publication_date",
    kind: "term",
    title: "Дата публикации",
    summary: "Когда отчёт или событие были опубликованы источником.",
    details:
      "Отчёт за I квартал может относиться к марту, но если его опубликовали 15 мая, на 1 апреля он ещё не был известен. Не выдумываем publication date.",
    relatedIds: ["known_at", "reporting_period", "point_in_time"],
  },
  known_at: {
    id: "known_at",
    kind: "term",
    title: "known_at",
    summary:
      "Дата, начиная с которой ProjectAI считает, что информация могла быть известна рынку.",
    details:
      "На решении as-of t допустимы только факты с known_at ≤ t. known_at может совпадать с publication_date или быть осторожнее; отсутствие known_at — риск look-ahead и повод для PARTIAL/NOT_READY.",
    interpretation: "Это операционный PIT-якорь ProjectAI, не «дата события в экономике».",
    limitations: ["Не путать с effective_date / record_date / period_end."],
    relatedIds: ["publication_date", "point_in_time", "report_age"],
  },
  point_in_time: {
    id: "point_in_time",
    kind: "term",
    title: "Point-in-Time (PIT)",
    summary: "На дату t разрешена только информация, которая уже могла быть известна ≤ t.",
    details:
      "Look-ahead leakage — жёсткая ошибка корректности. Фундаментальные отчёты, дивиденды и события входят в X(t) только через known_at / публикацию.",
    relatedIds: ["known_at", "publication_date", "fundamental_staleness"],
  },
  restatement: {
    id: "restatement",
    kind: "term",
    title: "Пересмотр отчёта (restatement)",
    summary: "Новая версия отчёта за тот же период; исторически известна только с её known_at.",
    details:
      "Нельзя задним числом подменять цифры, доступные на прошлую дату t. UI показывает Original → Restatement и какая версия была известна когда.",
    relatedIds: ["financial_report", "known_at", "source_provenance"],
  },
  IFRS: {
    id: "IFRS",
    kind: "term",
    title: "IFRS",
    summary: "Международные стандарты финансовой отчётности.",
    details:
      "International Financial Reporting Standards. Не предполагаем, что метрики IFRS всегда напрямую сопоставимы с RAS без нормализации.",
    relatedIds: ["RAS", "financial_report", "revenue"],
  },
  RAS: {
    id: "RAS",
    kind: "term",
    title: "РСБУ (RAS)",
    summary: "Российские стандарты бухгалтерского учёта.",
    details:
      "Russian Accounting Standards. Метрики могут отличаться по методике от IFRS; прямое сравнение без оговорок некорректно.",
    relatedIds: ["IFRS", "financial_report"],
  },
  revenue: {
    id: "revenue",
    kind: "metric",
    title: "Выручка",
    summary: "Доход от основной деятельности за отчётный период (как в источнике).",
    details: "Значение берётся из нормализованного факта отчёта. Не прогноз и не сигнал к покупке.",
    relatedIds: ["net_income", "margin", "financial_report"],
  },
  net_income: {
    id: "net_income",
    kind: "metric",
    title: "Чистая прибыль",
    summary: "Итоговый финансовый результат периода по отчёту.",
    details: "Зависит от стандарта (IFRS/RAS) и версии отчёта; смотрите known_at и restatement.",
    relatedIds: ["revenue", "EBITDA", "restatement"],
  },
  EBITDA: {
    id: "EBITDA",
    kind: "metric",
    title: "EBITDA",
    summary: "Распространённый proxy операционной прибыли; методика может отличаться.",
    details:
      "Не показываем EBITDA, если маппинг метрики ненадёжен. Не путать с чистой прибылью и не трактовать как рекомендацию.",
    limitations: ["Методика источника может отличаться.", "Не отображать при ненадёжном mapping."],
    relatedIds: ["net_income", "margin", "cash_flow"],
  },
  cash_flow: {
    id: "cash_flow",
    kind: "metric",
    title: "Денежный поток",
    summary: "Поток денежных средств из отчётности (операционный / свободный — как в факте).",
    details: "Точная статья зависит от нормализации факта. Без known_at не использовать в PIT-признаках.",
    relatedIds: ["EBITDA", "financial_report"],
  },
  margin: {
    id: "margin",
    kind: "metric",
    title: "Маржа",
    summary: "Отношение прибыли (или proxy) к выручке за период.",
    details: "Производная метрика; сравнима только при согласованном стандарте и версии отчёта.",
    relatedIds: ["revenue", "net_income", "EBITDA"],
  },
  dividend_recommendation: {
    id: "dividend_recommendation",
    kind: "term",
    title: "Рекомендация дивиденда",
    summary: "Предложение совета директоров / органа — ещё не утверждённый дивиденд.",
    details:
      "Рекомендация ≠ approval. До утверждения нельзя считать выплату фактом. На as-of t видна только стадия с known_at ≤ t.",
    limitations: ["Не инвестиционная рекомендация ProjectAI.", "Не путать с dividend_approval."],
    relatedIds: ["dividend_approval", "record_date", "dividend_yield"],
  },
  dividend_approval: {
    id: "dividend_approval",
    kind: "term",
    title: "Утверждение дивиденда",
    summary: "Официально утверждённый дивиденд (собрание акционеров / уполномоченный орган).",
    details: "После approval известны сумма и обычно ключевые даты. Recommendation без approval — более ранняя, менее финальная стадия.",
    relatedIds: ["dividend_recommendation", "record_date", "dividend_yield"],
  },
  record_date: {
    id: "record_date",
    kind: "term",
    title: "Record date",
    summary: "Дата фиксации реестра для права на дивиденд — не дата анонса.",
    details:
      "Record date ≠ announcement date. Известность рынку определяется known_at / публикацией, а не самим календарём выплат.",
    relatedIds: ["dividend_approval", "known_at", "dividend_yield"],
  },
  dividend_yield: {
    id: "dividend_yield",
    kind: "metric",
    title: "Дивидендная доходность",
    summary: "Производная от известной суммы дивиденда и рыночной цены.",
    details:
      "Не total-return учёт и не обещание будущей доходности. Считается только когда сумма уже known и есть цена.",
    limitations: ["Total-return accounting пока не ведётся.", "Не investment advice."],
    relatedIds: ["dividend_approval", "record_date"],
  },
  corporate_event: {
    id: "corporate_event",
    kind: "term",
    title: "Корпоративное событие",
    summary: "Структурированное событие эмитента: публикация отчёта, дивиденд, сплит и т.п.",
    details:
      "UI показывает структурированный timeline, а не сырой поток раскрытий. Для SPLIT известны события из market; known_at может отсутствовать у источника.",
    relatedIds: ["financial_report", "dividend_approval", "source_provenance"],
  },
  report_age: {
    id: "report_age",
    kind: "metric",
    title: "Возраст отчёта",
    summary: "Сколько дней прошло с known_at / публикации последнего usable отчёта.",
    details: "Большой возраст → фундаментальные признаки устаревают (staleness).",
    relatedIds: ["fundamental_staleness", "known_at", "financial_report"],
  },
  fundamental_staleness: {
    id: "fundamental_staleness",
    kind: "term",
    title: "Устаревание фундаментала",
    summary: "Насколько давно обновлялись отчётные факты относительно as-of даты.",
    details:
      "Даже корректный PIT-факт может быть экономически «старым». Staleness — отдельный quality/feature сигнал, не повод подтягивать будущие отчёты.",
    relatedIds: ["report_age", "point_in_time", "known_at"],
  },
  source_provenance: {
    id: "source_provenance",
    kind: "term",
    title: "Происхождение источника",
    summary: "Провайдер, ID, timestamps, hash и версия сырья — без засорения основного UI ссылками.",
    details:
      "В карточке доступно через «Технические детали». Нужно для аудита и воспроизводимости, не для торговых решений.",
    relatedIds: ["financial_report", "corporate_event", "restatement"],
  },
  cbr_hurdle: {
    id: "cbr_hurdle",
    kind: "metric",
    title: "Порог ключевой ставки ЦБ РФ",
    summary: "Минимальная экономическая планка для сравнения инвестиционной доходности.",
    details:
      "Excess return = доходность инвестиции минус доходность порога, начисленная за тот же период. Ключевая ставка не является безрисковой депозитной ставкой.",
    limitations: ["Публикуется с точностью даты.", "Не моделирует налоги и доступные банковские продукты."],
    relatedIds: ["excess_return", "known_at_quality"],
  },
  excess_return: {
    id: "excess_return",
    kind: "metric",
    title: "Excess return",
    summary: "Доходность стратегии сверх релевантного порога ключевой ставки.",
    details: "Сравниваются одинаковые даты и горизонт; издержки показываются отдельно.",
  },
  known_at_quality: {
    id: "known_at_quality",
    kind: "metric",
    title: "Точность known_at",
    summary: "DATE_ONLY означает известность только календарной даты, без точного времени публикации.",
    details: "В V0 ставка разрешена с даты наблюдения и никогда не используется раньше неё.",
  },
  dirty_price: {
    id: "dirty_price",
    kind: "metric",
    title: "Грязная цена облигации",
    summary: "Чистая цена плюс накопленный купонный доход (НКД).",
    details: "Именно грязная стоимость вместе с комиссиями определяет требуемые деньги.",
  },
  nkd: {
    id: "nkd",
    kind: "metric",
    title: "НКД",
    summary: "Накопленный купонный доход между датами выплаты купона.",
    details: "При покупке выплачивается продавцу сверх чистой цены.",
  },
  bond_offer: {
    id: "bond_offer",
    kind: "metric",
    title: "Оферта облигации",
    summary: "Право предъявить облигацию на условиях оферты; это не автоматическое погашение.",
    details: "Без явной политики исполнения инструмент остаётся RESEARCH_ONLY.",
  },
  credit_quality: {
    id: "credit_quality",
    kind: "metric",
    title: "Кредитное качество",
    summary: "Наблюдаемая оценка способности эмитента обслуживать долг.",
    details: "UNKNOWN для корпоративной облигации запрещает считать её безопасной или готовой для реального портфеля.",
  },
  integer_lots: {
    id: "integer_lots",
    kind: "metric",
    title: "Целые лоты",
    summary: "Реалистичный расчёт покупает только целое число биржевых лотов.",
    details: "Остаток остаётся деньгами; отрицательный остаток запрещён.",
  },
  transaction_costs: {
    id: "transaction_costs",
    kind: "metric",
    title: "Транзакционные издержки",
    summary: "Комиссии брокера и биржи плюс slippage.",
    details: "Slippage повышает цену BUY и снижает цену SELL, но не применяется к купонам и погашению.",
  },
  tax_not_modeled: {
    id: "tax_not_modeled",
    kind: "metric",
    title: "Налоги не моделируются",
    summary: "Статус NOT_MODELED: калькулятор не выдаёт вымышленные налоговые суммы.",
    details: "Итоговые значения до налогов.",
  },
  bond_coupon_schedule: {
    id: "bond_coupon_schedule",
    kind: "metric",
    title: "График купонов",
    summary: "Даты и суммы выплат купона, как их отдаёт официальный источник MOEX bondization.",
    details:
      "Суммы не выдумываются из текущей ставки задним числом. Если будущий купон без суммы — бумага не SUPPORTED.",
  },
  bond_amortization: {
    id: "bond_amortization",
    kind: "metric",
    title: "Амортизация",
    summary: "Частичное погашение номинала до финальной даты.",
    details:
      "Сложная амортизация пока RESEARCH_ONLY: Kraken сохраняет факты, но не делает вид, что всё поддержано.",
  },
  bond_redemption: {
    id: "bond_redemption",
    kind: "metric",
    title: "Погашение",
    summary: "Финальный возврат номинала в дату maturity.",
    details: "Не путать с офертой: погашение — обязательство эмитента по графику.",
  },
  bond_supported: {
    id: "bond_supported",
    kind: "metric",
    title: "SUPPORTED",
    summary: "Денежные потоки бумаги достаточно надёжны для учёта as-of сейчас.",
    details:
      "Это не оценка безопасности. Корпоративная бумага без рейтинга остаётся непригодной для реального портфеля.",
  },
  bond_research_only: {
    id: "bond_research_only",
    kind: "metric",
    title: "RESEARCH_ONLY",
    summary: "Данных не хватает или структура слишком сложная для честной поддержки.",
    details: "Примеры: незафиксированные купоны, будущая оферта, сложная амортизация.",
  },
  bond_ytm: {
    id: "bond_ytm",
    kind: "metric",
    title: "YTM",
    summary: "Доходность к погашению, если источник её публикует.",
    details:
      "В V1 берём наблюдаемый YIELD MOEX. При оферте нельзя считать YTM to maturity единственной истиной.",
  },
  bond_known_at: {
    id: "bond_known_at",
    kind: "metric",
    title: "known_at для купонов",
    summary: "Когда график купонов стал известен рынку.",
    details:
      "MOEX bondization сейчас даёт CURRENT_STATE_ONLY: текущее состояние графика без архива ревизий. Этого мало для исторической стратегии без look-ahead.",
  },
  accounting_vs_credit: {
    id: "accounting_vs_credit",
    kind: "metric",
    title: "Учёт потоков vs кредитный риск",
    summary: "Уметь посчитать купоны ≠ бумага безопасна.",
    details:
      "Accounting support отвечает на «какие деньги придут по графику». Credit quality отвечает на «доживёт ли эмитент до выплат».",
  },
  asset_allocation: {
    id: "asset_allocation",
    kind: "metric",
    title: "Asset allocation",
    summary: "Решение, какую долю капитала держать в акциях, облигациях и деньгах.",
    details: "Не заменяет модели: использует их результат и сравнивает с hurdle без magic score.",
  },
  equity_sleeve: {
    id: "equity_sleeve",
    kind: "metric",
    title: "Equity sleeve",
    summary: "Доля капитала, выделенная под Equity Alpha.",
    details: "Может быть снижена, если ожидаемая премия над ключевой ставкой недостаточна.",
  },
  fixed_income_sleeve: {
    id: "fixed_income_sleeve",
    kind: "metric",
    title: "Fixed Income sleeve",
    summary: "Доля капитала в облигациях.",
    details:
      "Облигация не всегда безопасна. Корпоративные бумаги без credit quality не годятся для реального портфеля.",
  },
  cash_sleeve: {
    id: "cash_sleeve",
    kind: "metric",
    title: "Cash sleeve",
    summary: "Денежная альтернатива относительно порога ЦБ.",
    details: "Иногда рационально не покупать риск, если премия не окупает его.",
  },
  allocation_weight: {
    id: "allocation_weight",
    kind: "metric",
    title: "Allocation weight",
    summary: "Целевой вес sleeve до учёта целых лотов.",
    details: "После лотов фактические суммы могут отличаться; остаток остаётся cash.",
  },
  expected_excess_return: {
    id: "expected_excess_return",
    kind: "metric",
    title: "Expected excess return",
    summary: "Ожидаемая доходность минус релевантный hurdle за тот же горизонт.",
    details: "Без калибровки модели качество прогноза = UNKNOWN.",
  },
  hurdle: {
    id: "hurdle",
    kind: "metric",
    title: "Hurdle",
    summary: "Экономический порог сравнения — в V0 прежде всего ключевая ставка ЦБ РФ.",
    details: "Не депозитная гарантия и не обещание доступной доходности инвестору.",
  },
  risk_premium: {
    id: "risk_premium",
    kind: "metric",
    title: "Risk premium",
    summary: "Надбавка за риск относительно более консервативной альтернативы.",
    details: "Если премия недостаточна, Kraken может уменьшить долю акций.",
  },
  liquidity: {
    id: "liquidity",
    kind: "metric",
    title: "Liquidity",
    summary: "Способность перестроить портфель без чрезмерных издержек.",
    details: "V0 учитывает флаг stale prices / liquidity state без отдельного Risk Engine.",
  },
  concentration: {
    id: "concentration",
    kind: "metric",
    title: "Concentration",
    summary: "Насколько капитал сосредоточен в малом числе позиций.",
    details: "Ограничения max_single_position задаются research configuration, не оптимизацией.",
  },
};

export const HELP_PAGES: Record<string, PageHelpContent> = {
  overview: {
    id: "overview",
    title: "Обзор",
    about: "Сводка здоровья платформы, рыночных данных и недавних процессов.",
    understand: [
      "Работают ли ключевые сервисы",
      "Есть ли свежие рыночные данные",
      "Какие процессы недавно выполнялись",
    ],
    metrics: ["data_quality"],
    interpret: [
      "Сначала смотрите статус сервисов и свежесть данных.",
      "Ошибки DQ важнее предупреждений.",
    ],
    limitations: ["Это operational overview, не торговый дашборд."],
  },
  market: {
    id: "market",
    title: "Рыночные данные",
    about: "Каталог инструментов, источники MOEX/ЦБ и вкладка «Исторический архив».",
    understand: [
      "Какие инструменты загружены в рабочий контур",
      "Диапазон доступной MOEX-истории",
      "Что показывает внешний архив и почему он не заменяет MOEX",
      "Как выглядят survivorship bias и RAW vs adjusted",
    ],
    metrics: [
      "last_price",
      "data_quality",
      "raw_candles",
      "external_history",
      "historical_universe",
      "survivorship_bias",
      "raw_price",
      "adjusted_price",
      "source_reconciliation",
      "source_precedence",
      "canonical_market_data",
    ],
    interpret: [
      "Вкладка «Инструменты» — operational cohort.",
      "Вкладка «Исторический архив» — research staging, не live trading.",
      "Если обучать модель только на компаниях, которые дожили до сегодня, прошлый результат может быть слишком хорошим.",
    ],
    limitations: [
      "UI показывает RAW-историю рабочего контура, не portfolio P&L.",
      "Архив не загружается из браузера (только операторский CLI).",
    ],
  },
  instrument: {
    id: "instrument",
    title: "Инструмент",
    about: "Карточка инструмента: обзор, котировки, загрузки, DQ, аналитика и technical.",
    understand: [
      "История RAW-цен и выбранный период",
      "Последние признаки Analytics",
      "Техническое состояние rules_v1",
    ],
    metrics: [
      "last_price",
      "raw_candles",
      "return_20d",
      "rsi14",
      "confidence",
      "technical_score",
    ],
    interpret: [
      "Вкладка «Котировки» — исследование периода по RAW close.",
      "Analytics и Technical — производные слои, не приказы.",
    ],
    limitations: [
      "Короткая история (T/YDEX и аналоги) ограничивает длинные пресеты.",
      "Не переключаемся на adjusted цены.",
    ],
  },
  analytics: {
    id: "analytics",
    title: "Аналитика",
    about: "Версионируемые производные признаки из рыночных данных (feature sets).",
    understand: [
      "Какой feature set активен",
      "Покрытие инструментов",
      "История расчётов признаков",
    ],
    metrics: ["return_1d", "return_5d", "return_20d", "volatility_20d", "feature_coverage"],
    interpret: [
      "Признаки — входы для моделей, не рекомендации.",
      "Mechanical V2 — отдельный набор; не активируется этим экраном.",
    ],
    limitations: ["UI не запускает ML-обучение."],
  },
  relations: {
    id: "relations",
    title: "Связи",
    about: "Статистическая структура рынка: корреляции и lead-lag.",
    understand: [
      "Какие пары сильнее связаны на окне",
      "Есть ли выраженный лаг",
      "Насколько snapshot валиден",
    ],
    metrics: ["relations_term", "pearson", "spearman", "best_lag"],
    interpret: [
      "Топ связей зависит от окна, фильтра |corr| и поиска.",
      "Pair explorer показывает профиль лагов выбранной пары.",
    ],
    limitations: [
      "Корреляция ≠ причинность.",
      "Не выдача BUY/SELL.",
    ],
  },
  technical: {
    id: "technical",
    title: "Технический анализ",
    about: "Rules_v1: score, direction и confidence по тренду, моментуму, RSI и объёму.",
    understand: [
      "Распределение бычьих/нейтральных/медвежьих состояний",
      "Сигналы по инструментам на as_of",
      "Качество и confidence",
    ],
    metrics: ["technical_score", "confidence", "rsi14", "sma20_distance", "atr14_pct", "return_20d"],
    interpret: [
      "Сортируйте по confidence осторожно: это не вероятность прибыли.",
      "Invalid / предупреждения важнее «красивого» score.",
    ],
    limitations: ["Не рекомендация к сделке.", "Не брокерский сигнал."],
  },
  workflows: {
    id: "workflows",
    title: "Процессы",
    about:
      "Фоновые задачи загрузки, DQ, analytics, relations, technical и ежедневный исследовательский цикл.",
    understand: [
      "Состояние ежедневного исследовательского цикла",
      "Какие задачи бегут сейчас",
      "Где упал шаг",
      "Длительность и статус",
    ],
    metrics: ["research_cycle", "daily_cycle_health", "forward_outcome_pending"],
    interpret: [
      "Карточка цикла сверху — операционный контур Forward/Shadow.",
      "Открывайте процесс, чтобы увидеть timeline шагов.",
    ],
    limitations: ["Это журнал оркестрации, не бизнес-отчёт."],
  },
  system: {
    id: "system",
    title: "Система",
    about: "Здоровье сервисов, сведения о сборке и техническая диагностика.",
    understand: ["Доступность БД/Redis/worker", "События диагностики"],
    metrics: [],
    interpret: ["При деградации сначала смотрите сервисный статус, затем tech events."],
    limitations: ["Не заменяет мониторинг инфраструктуры вне Docker-стека."],
  },
  simulator: {
    id: "simulator",
    title: "Симуляции",
    about: "Список прогонов Historical Simulator V0: сегменты DEV OOS и HOLDOUT, издержки, метрики.",
    understand: [
      "Какие research-прогоны сохранены",
      "Разница сегментов и commission bps",
      "Куда перейти за кривой NAV и инспектором дня",
    ],
    metrics: ["sim_nav", "sim_cagr", "sim_max_drawdown", "sim_bps", "sim_oos", "sim_holdout"],
    interpret: [
      "HOLDOUT визуально отделён от DEV — это разные периоды оценки.",
      "Engineering PASS ≠ прибыльность.",
    ],
    limitations: [
      "Research dashboard, не live trading.",
      "Числа зависят от spec (bps, policy, capital).",
    ],
  },
  simulator_run: {
    id: "simulator_run",
    title: "Симуляция портфеля",
    about:
      "Дашборд одного прогона: NAV vs IMOEX, просадка, инспектор даты, fills provenance, cost sensitivity, DEV/HOLDOUT.",
    understand: [
      "Абсолютная доходность vs относительный результат в п.п.",
      "Поведение капитала на выбранном окне",
      "Фактические причины сделок без LLM",
      "Краткое объяснение → Подробнее → Технические детали",
    ],
    metrics: [
      "sim_nav",
      "sim_cagr",
      "sim_excess",
      "sim_max_drawdown",
      "sim_sharpe",
      "sim_turnover",
      "sim_commission",
      "sim_survivorship",
      "sim_oos",
      "sim_holdout",
      "sim_rebalance",
      "sim_next_open",
      "decision_why",
      "decision_pred_20d",
      "decision_rank",
    ],
    interpret: [
      "Отрицательная «Доходность портфеля» — убыток; положительный excess может быть при общем падении рынка.",
      "MIXED — research-контекст Candidate V0, отделён от engineering PASS.",
      "Клик по графику открывает day inspector.",
    ],
    limitations: [
      "Survivorship bias universe.",
      "Без дивидендов.",
      "IMOEX price index.",
      "Не разрешение на реальные деньги.",
    ],
  },
  shadow: {
    id: "shadow",
    title: "Живой эксперимент",
    about:
      "Проспективный Shadow Portfolio: Forward Signal → решения → ожидание будущего OPEN → fills/NAV. Не historical backtest.",
    understand: [
      "Что такое живой эксперимент и чем он отличается от симулятора",
      "Почему пока может не быть сделок",
      "Почему нельзя использовать прошлые OPEN",
      "Разница as_of / generated_at",
      "Что такое Forward Signal",
      "Чем портфель A отличается от B",
      "Почему сравнение станет полезнее со временем",
      "Почему ранние результаты нельзя считать доказательством прибыльности",
    ],
    metrics: [
      "shadow_portfolio",
      "forward_signal",
      "prospective_experiment",
      "activation_date",
      "pending_order",
      "market_watermark",
      "signal_as_of",
      "signal_generated_at",
      "risk_state",
      "experiment_age",
      "decision_why",
      "research_cycle",
      "daily_cycle_health",
      "forward_outcome_pending",
    ],
    interpret: [
      "0 fills при PENDING — корректный старт.",
      "A и B стартуют одинаково; DD Guard на B проявится только после реальной просадки.",
      "Решения объясняются Decision Explanation UX без LLM.",
      "Операционная полоса сверху отражает ежедневный цикл и зрелость 20d outcomes.",
    ],
    limitations: [
      "Автоматическое расписание зависит от DAILY_RESEARCH_CYCLE_ENABLED.",
      "Нет дивидендов / total return.",
      "Короткий горизонт ≠ proof of edge.",
      "Не брокер и не рекомендации.",
    ],
  },
  research_lab: {
    id: "research_lab",
    title: "Лаборатория",
    about:
      "Исторические исследовательские эксперименты с моделями, портфельными политиками и издержками. Не живой Shadow и не обучение модели.",
    understand: [
      "Что такое Лаборатория и чем она отличается от Живого эксперимента",
      "Что можно менять: модель из реестра, политика, risk, издержки, период, капитал",
      "Что нельзя: параметры Top20/Top35/−20%, обучение Candidate, HOLDOUT для тюнинга",
      "Что такое Development OOS и почему HOLDOUT заблокирован",
      "Зачем смотреть Return рядом с Max DD и Turnover",
    ],
    metrics: [
      "research_lab",
      "research_not_live",
      "development_oos",
      "observed_holdout",
      "candidate_model",
      "ranking_model",
      "ranking_score",
      "rank_ic",
      "portfolio_policy",
      "risk_policy",
      "simulation_cost",
      "research_period",
      "experiment_reuse",
      "quick_comparison",
      "model_quality",
      "economic_viability",
      "paired_prospective_model",
      "sim_max_drawdown",
      "sim_turnover",
      "sim_sharpe",
    ],
    interpret: [
      "Высокая доходность сама по себе не делает эксперимент «лучшим».",
      "Повтор той же конфигурации по умолчанию переиспользует существующий результат.",
    ],
    limitations: [
      "Не оптимизатор параметров.",
      "Не меняет Forward/Shadow.",
      "Не обучает Candidate V1.",
    ],
  },
  research_compare: {
    id: "research_compare",
    title: "Сравнение экспериментов",
    about: "Сопоставление 2–5 исторических прогонов по метрикам и кривым NAV/просадки.",
    understand: [
      "Fair comparison: одинаковые период, политика, риск, издержки, капитал, исполнение; модель может отличаться",
      "Почему V0 vs V1 при фиксированной политике — честное сравнение моделей",
      "Семейство издержек 0/5/10/20 bps",
      "Почему ниже Max DD может сопровождаться ниже Return",
      "Почему ниже Turnover важен при ненулевых издержках",
      "Почему уже наблюдавшийся HOLDOUT нельзя считать свежей проверкой",
      "Денежная альтернатива — пост-обработка, не часть симуляции",
    ],
    metrics: [
      "fair_comparison",
      "comparison_family",
      "observed_holdout",
      "candidate_model",
      "ranking_model",
      "sim_excess",
      "sim_max_drawdown",
      "sim_turnover",
      "sim_sharpe",
      "simulation_cost",
      "cash_hurdle",
      "excess_vs_cash",
    ],
    interpret: [
      "Наблюдения формулируются нейтрально по метрикам — без «лучшей стратегии» и Champion.",
    ],
    limitations: [
      "Сравнение не запускает оптимизацию.",
      "Периоды могут не совпадать — это явно помечается.",
    ],
  },
  research_diagnostics: {
    id: "research_diagnostics",
    title: "Диагностика моделей",
    about:
      "Разбор качества ранжирования, верхней части списка, стабильности, расхождений и экономического смысла V0/V1.",
    understand: [
      "Чем качество модели отличается от перевода в портфель и от экономического смысла",
      "Почему общий Rank IC не гарантирует хороший портфель",
      "Как читать Top-tail и загрязнение топа",
      "Зачем смотреть стабильность рейтинга рядом с оборотом",
      "Что показывает explorer расхождений",
      "Денежная альтернатива — исследовательский benchmark",
    ],
    metrics: [
      "model_quality",
      "portfolio_translation",
      "economic_viability",
      "cash_hurdle",
      "excess_vs_cash",
      "top_tail_quality",
      "rank_stability",
      "model_disagreement",
      "regime_analysis",
      "rank_ic",
      "break_even_cost",
    ],
    interpret: [
      "Выводы детерминированные и фактологические — без investment advice.",
      "Красная «тревога» не используется: только исследовательский тон.",
    ],
    limitations: [
      "Историческая диагностика ≠ будущая доходность.",
      "Survivorship и упрощённые издержки сохраняются.",
    ],
  },
  research_prospective: {
    id: "research_prospective",
    title: "Проспективное сравнение V0/V1",
    about:
      "Парный эксперимент только вперёд: одинаковые признаки, политика и риск; отличается только модель.",
    understand: [
      "Почему пустой старт после активации — нормальное состояние",
      "Стадии конвейера от активации до оценки",
      "V0 expected return можно показывать как %, V1 ranking score — нельзя",
      "Зрелость выборки и запрет на язык победителя при малой выборке",
      "Согласие моделей ≠ правота одной из них",
    ],
    metrics: [
      "paired_prospective_model",
      "sample_maturity",
      "rank_correlation",
      "top20_overlap",
      "ranking_score",
      "prospective_experiment",
      "forward_outcome_pending",
    ],
    interpret: [
      "Пока зрелых дат мало — только наблюдение процесса, не вердикт о edge.",
    ],
    limitations: [
      "Нет исторического paired backfill.",
      "Не смешивается с операционным Shadow Hysteresis.",
    ],
  },
  investment: {
    id: "investment",
    title: "Облигации и инвестиционный контур",
    about:
      "Ключевая ставка ЦБ как порог, график купонов MOEX, поддержка учёта потоков и честные ограничения.",
    understand: [
      "Чем купон, амортизация, оферта и погашение отличаются",
      "Почему known_at для графика купонов может быть только CURRENT_STATE_ONLY",
      "Что значит SUPPORTED и RESEARCH_ONLY",
      "Почему учёт потоков не равен кредитной безопасности",
      "Как комиссии и целые лоты влияют на остаток 100 000 ₽",
    ],
    metrics: [
      "cbr_hurdle",
      "excess_return",
      "known_at_quality",
      "bond_known_at",
      "dirty_price",
      "nkd",
      "bond_coupon_schedule",
      "bond_amortization",
      "bond_redemption",
      "bond_offer",
      "bond_supported",
      "bond_research_only",
      "bond_ytm",
      "credit_quality",
      "accounting_vs_credit",
      "integer_lots",
      "transaction_costs",
      "tax_not_modeled",
    ],
    interpret: [
      "SUPPORTED — можно честно считать денежные потоки as-of сейчас.",
      "RESEARCH_ONLY — не хватает надёжных данных или мешает оферта/амортизация.",
      "Корпоративная бумага без credit quality не годится для реального портфеля 100 000 ₽.",
    ],
    limitations: [
      "Исторический total return облигаций NOT_READY: нет архива ревизий графика.",
      "Налоги и settlement не моделируются.",
      "Нет брокерского API и исполнения.",
    ],
  },
  allocation: {
    id: "allocation",
    title: "Распределение капитала",
    about:
      "Research foundation: куда Kraken направил бы капитал между Equity Alpha, Fixed Income и Cash.",
    understand: [
      "Почему Kraken не обязан всегда покупать акции",
      "Чем equity / fixed income / cash sleeves отличаются",
      "Как hurdle и expected excess return влияют на веса",
      "Почему нет magic investment_score",
      "Как целевые веса превращаются в целые лоты на 100 000 ₽",
    ],
    metrics: [
      "asset_allocation",
      "equity_sleeve",
      "fixed_income_sleeve",
      "cash_sleeve",
      "allocation_weight",
      "expected_excess_return",
      "hurdle",
      "cbr_hurdle",
      "risk_premium",
      "liquidity",
      "concentration",
      "credit_quality",
      "integer_lots",
    ],
    interpret: [
      "Сравнение политик — исследовательское, без автовыбора победителя.",
      "INSUFFICIENT_DATA лучше, чем угаданные веса.",
    ],
    limitations: [
      "Нет ML/оптимизации весов по истории.",
      "Нет реального исполнения и брокера.",
      "Калибровка equity-моделей пока UNKNOWN.",
    ],
  },
  fundamentals: {
    id: "fundamentals",
    title: "Фундаментал и события",
    about:
      "Отчётность, дивиденды и корпоративные события эмитентов с явным учётом known_at и даты публикации.",
    understand: [
      "Почему дата публикации важнее «месяца отчётного периода»",
      "Что такое known_at и Point-in-Time",
      "Чем IFRS отличается от РСБУ (RAS) и почему метрики не всегда сопоставимы",
      "Почему рекомендация дивиденда ≠ утверждение",
      "Как as-of explorer показывает, что было известно на дату",
      "Почему пустые таблицы при недоступных лентах — честное NOT_READY",
    ],
    metrics: [
      "fundamental_data",
      "financial_report",
      "reporting_period",
      "publication_date",
      "known_at",
      "point_in_time",
      "restatement",
      "IFRS",
      "RAS",
      "revenue",
      "net_income",
      "EBITDA",
      "cash_flow",
      "margin",
      "dividend_recommendation",
      "dividend_approval",
      "record_date",
      "dividend_yield",
      "corporate_event",
      "report_age",
      "fundamental_staleness",
      "source_provenance",
    ],
    interpret: [
      "Сначала смотрите PIT-карточку и статус качества (GOOD / PARTIAL / NOT_READY).",
      "Не трактуйте фундаментальные цифры как investment advice.",
      "ML readiness описывает кандидатов признаков и блокеры — без запуска обучения.",
    ],
    limitations: [
      "Живые бесплатные дивидендные/отчётные ленты MOEX могут быть недоступны.",
      "Не обучает Candidate и не меняет Dataset V2 / Forward / Shadow.",
      "Не подменяет RAW market.candles.",
    ],
  },
};

export function getMetricHelp(id: string): HelpEntry | undefined {
  return HELP_METRICS[id];
}

export function getPageHelp(id: string): PageHelpContent | undefined {
  return HELP_PAGES[id];
}

export function resolveHelpEntry(id: string): HelpEntry | undefined {
  return HELP_METRICS[id];
}
